version: "3"

services:

    # A PostgreSQL instance containing schemas from CDMSs that use PostgreSQL (currently clide and wmdr)
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password


    # A MariaDB instance containing schemas from CDMSs that use MySQL/MariaDB (currently climsoft-4.1.1 and mch-english)
    mariadb:
        image: mariadb:10.1
        container_name: mariadb
        command: --default-authentication-plugin=mysql_native_password --collation_server=utf8_general_ci --character_set_server=utf8 --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=test
