server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fr-CA
    cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
logging:
    level: ERROR

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://api.opencdms.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: OpenCDMS
        url: https://pygeoapi.io
    contact:
        name: Admin, OpenCDMS
        position: Admin
        address: info@opencdms.org
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: England
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: info@opencdms.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    climsoft:
        type: collection
        title: Climsoft Observationfinal
        description: Climsoft observations
        keywords:
            - climsoft
            - observation
        languages:
            - en-US
            - fr-CA
        context:
            -   schema: https://schema.org/
                obsDatetime:
                    "@id": schema:observationDate
                    "@type": schema:DateTime
                value:
                    "@id": schema:value
                    "@type": schema:Number
        links:
            -   type: text/csv
                rel: canonical
                title: example data
                href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
                hreflang: en-US
        extents:
#            spatial:
#                bbox: [ -180,-90,180,90 ]
#                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1960-10-30T18:24:39Z
                end: 2022-10-30T08:57:29Z
        providers:
            -   type: feature
                editable: true
                name: opencdms.pygeoapi.non_spatial_provider.ClimsoftProvider
                languages:
                    - en
                    - fr
                data:
                    host: 127.0.0.1
                    port: 23306 # Default 3306 if not provided
                    dbname: mariadb_climsoft_test_db_v4
                    user: root
                    password: password

#    surface:
#        type: collection
#        title: Surface observation data
#        description: Surface observation data from raw_data
#        keywords:
#            - climsoft
#            - observation
#        languages:
#            - en-US
#            - fr-CA
#        context:
#            -   schema: https://schema.org/
#                datetime:
#                    "@id": schema:observationDate
#                    "@type": schema:DateTime
#                value:
#                    "@id": schema:value
#                    "@type": schema:Number
#        links:
#            -   type: text/csv
#                rel: canonical
#                title: example data
#                href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
#                hreflang: en-US
#        extents:
#            spatial:
#                bbox: [ -180,-90,180,90 ]
#                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
#            temporal:
#                begin: 1960-10-30T18:24:39Z
#                end: 2022-10-30T08:57:29Z
#        providers:
#            -   type: feature
#                editable: true
#                name: opencdms.pygeoapi.surface_provider.SurfaceProvider
#                languages:
#                    - en
#                    - fr
#                data:
#                    host: 127.0.0.1
#                    port: 45432 # Default 5432 if not provided
#                    dbname: postgres
#                    user: postgres
#                    password: password
