FROM postgres:13
COPY /opencdms/opencdms-test-data/scripts/entrypoints/clide.sh /docker-entrypoint-initdb.d/1.sh
COPY /opencdms/opencdms-test-data/schemas/clide/clidedb_schema.sql /docker-entrypoint-initdb.d/2.sql
COPY /opencdms/opencdms-test-data/schemas/wmdr/wmdr_ddl.sql /docker-entrypoint-initdb.d/3.sql
