FROM mariadb:10.1
COPY schemas/climsoft/v4/v4.1.1/climsoft_v4_all.sql /docker-entrypoint-initdb.d/1.sql
COPY scripts/entrypoints/mch-english.sql /tmp/settings.sql
COPY schemas/mch/Create_MCH_English_basic_tables.sql /tmp/ddl.sql
RUN cat /tmp/settings.sql /tmp/ddl.sql > /docker-entrypoint-initdb.d/2.sql
