/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-May-2021 13:23:48 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Abstractenvironmentalmonitoringfacility" CASCADE
;

DROP TABLE IF EXISTS "Attribution" CASCADE
;

DROP TABLE IF EXISTS "Climatezone" CASCADE
;

DROP TABLE IF EXISTS "Controlcheckreport" CASCADE
;

DROP TABLE IF EXISTS "Datageneration" CASCADE
;

DROP TABLE IF EXISTS "Datapolicy" CASCADE
;

DROP TABLE IF EXISTS "Deployment" CASCADE
;

DROP TABLE IF EXISTS "Description" CASCADE
;

DROP TABLE IF EXISTS "Equipment" CASCADE
;

DROP TABLE IF EXISTS "EquipmentEquipment" CASCADE
;

DROP TABLE IF EXISTS "Equipmentlog" CASCADE
;

DROP TABLE IF EXISTS "Eventreport" CASCADE
;

DROP TABLE IF EXISTS "Facilitylog" CASCADE
;

DROP TABLE IF EXISTS "Facilityset" CASCADE
;

DROP TABLE IF EXISTS "FacilitySetObservingFacility" CASCADE
;

DROP TABLE IF EXISTS "Frequencies" CASCADE
;

DROP TABLE IF EXISTS "Geospatiallocation" CASCADE
;

DROP TABLE IF EXISTS "Header" CASCADE
;

DROP TABLE IF EXISTS "Instrumentoperatingstatus" CASCADE
;

DROP TABLE IF EXISTS "Log" CASCADE
;

DROP TABLE IF EXISTS "Logentry" CASCADE
;

DROP TABLE IF EXISTS "Maintenancereport" CASCADE
;

DROP TABLE IF EXISTS "Observingcapability" CASCADE
;

DROP TABLE IF EXISTS "Observingfacility" CASCADE
;

DROP TABLE IF EXISTS "Population" CASCADE
;

DROP TABLE IF EXISTS "Process" CASCADE
;

DROP TABLE IF EXISTS "Processing" CASCADE
;

DROP TABLE IF EXISTS "Programaffiliation" CASCADE
;

DROP TABLE IF EXISTS "Reporting" CASCADE
;

DROP TABLE IF EXISTS "Reportingstatus" CASCADE
;

DROP TABLE IF EXISTS "Responsibleparty" CASCADE
;

DROP TABLE IF EXISTS "Resultset" CASCADE
;

DROP TABLE IF EXISTS "Sampling" CASCADE
;

DROP TABLE IF EXISTS "Schedule" CASCADE
;

DROP TABLE IF EXISTS "Surfacecover" CASCADE
;

DROP TABLE IF EXISTS "Surfaceroughness" CASCADE
;

DROP TABLE IF EXISTS "Territory" CASCADE
;

DROP TABLE IF EXISTS "Timezone" CASCADE
;

DROP TABLE IF EXISTS "Topographybathymetry" CASCADE
;

DROP TABLE IF EXISTS "Wigosmetadatarecord" CASCADE
;

/* Create Tables */

CREATE TABLE "Abstractenvironmentalmonitoringfacility"
(
	"Description" varchar(50) NULL,	-- 4-05 Non-formalized information about the location and surroundings at which an observation is made and that may influence it. In WIGOS, description is used to describe an observingFacility or Equipment. 
	"Extension" varchar(50) NULL,	-- This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks. However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. 
	"Geospatiallocation" varchar(50) NULL,	-- 3-07 Position in space defining the location of the environmental monitoring station/platform at the time of observation.  5-12 Geospatial location of instrument/sensor
	"Onlineresource" varchar(50) NULL,	-- An online resource containing additional information about the facility or equipment
	"Responsibleparty" varchar(50) NULL,	-- The organisation responsible.
	"AbstractenvironmentalmonitoringfacilityID" integer NOT NULL
)
;

CREATE TABLE "Attribution"
(
	"Originator" varchar(50) NULL,	-- Identifies the individual and/or organization at the origin of the resource. This is typically the owner of the ressource, e.g., a data set.
	"Originatorurl" varchar(50) NULL,
	"Source" varchar(50) NULL,
	"Title" varchar(50) NULL,	-- The title of the attributed work.
	"AttributionID" integer NOT NULL
)
;

CREATE TABLE "Climatezone"
(
	"Climatezone" varchar(50) NULL,	-- 4-07 type of climate zone at the facility. From the ClimateZoneType codelist.
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.
	"ClimatezoneID" integer NOT NULL
)
;

CREATE TABLE "Controlcheckreport"
(
	"Alternateuri" varchar(50) NULL,	-- 5-08 Alternatively the summary of the control check may be provided via a URI that resolves to a document containing this information.
	"Checklocation" varchar(50) NULL,	-- 5-08 Location of sensor when check was performed (e.g. in-situ, offsite etc.) From codelist ControlCheckLocationType.
	"Controlcheckresult" varchar(50) NULL,	-- 5-08 Result of the control check, from InstrumentControlResultType codelist
	"Periodofvalidity" varchar(50) NULL,	-- 5-08 period of validity of the control check (e.g. 4 years)
	"Standardname" varchar(50) NULL,	-- 5-08 Nameof the Standard used.
	"Standardserialnumber" varchar(50) NULL,	-- 5-08 Serial Number of the standard used.
	"Standardtype" varchar(50) NULL,	-- 5-08 Type of the Standard used. From the StandardType code list.
	"Withinverificationlimit" boolean NULL,	-- 5-08 Was the instrument found to be within verification limits (True if yes, False if no)
	"ControlcheckreportID" integer NOT NULL
)
;

CREATE TABLE "Datageneration"
(
	"Validperiod" varchar(50) NULL,	-- The period of time for which this processing arrangement was/is in place. (Note: this time period must fall within the time period specified in the Deployment).
	"DatagenerationID" integer NOT NULL,
	"DeploymentID" integer NULL
)
;

CREATE TABLE "Datapolicy"
(
	"Attribution" varchar(50) NULL,	-- Describes the attribution details pertinent to dataPolicy
	"Datapolicy" varchar(50) NULL,	-- 9-02 Details relating to the use and limitations surrounding data imposed by the supervising organization.
	"DatapolicyID" integer NOT NULL
)
;

CREATE TABLE "Deployment"
(
	"Applicationarea" varchar(50) NULL,	-- 2-01 The context within, or intended application(s) for which the observation is primarily made or which has/have the most stringent requirements.
	"Communicationmethod" varchar(50) NULL,	-- 3-08 The primary data communication method, from the DataCommunicationMethodType codelist.
	"Configuration" varchar(50) NULL,	-- 5-06 Description of any shielding or configuration/setup of the instrumentation.
	"Controlschedule" varchar(50) NULL,	-- 5-07 Description of schedule for calibrations or verification of instrument.
	"Exposure" varchar(50) NULL,	-- 5-15 The degree to which an instrument is affected by external influences according to the CIMO classification. Value from ExposureType codelist.
	"Heightabovelocalreferencesurface" varchar(50) NULL,	-- 5-05 Vertical distance of sensor from specified reference surface, in the direction away from the earth's center. Positive values indicate above reference surface, negative values indicate below references surface (e.g., below ocean surface).
	"Instrumentoperatingstatus" varchar(50) NULL,	-- 5-04 The operational status of the instrument when deployed (Operational, testing etc.).
	"Localreferencesurface" varchar(50) NULL,	-- 5-05 Description of the specified reference surface taken from the codelist LocalReferenceSurfaceType
	"Maintenanceschedule" varchar(50) NULL,	-- 5-10 A description (and schedule) of maintenance that is routinely performed on an instrument
	"Representativeness" varchar(50) NULL,	-- 1-05 An assessment of the representativeness of the observations from the RepresentativenessType codelist.
	"Sourceofobservation" varchar(50) NULL,	-- 5-01 The source of the observation (manual, automatic, visual etc.) from the SourceOfObservationType codelist.
	"Validperiod" varchar(50) NULL,	-- The period of time for which this deployment configuration was/is in place. (Note: this time period must fall within the time period specified in the OM_Observation phenomenonTime)
	"DeploymentID" integer NOT NULL,
	"ProcessID" integer NULL
)
;

CREATE TABLE "Description"
(
	"Description" varchar(50) NULL,	-- 4-05 Non-formalized information about the location and surroundings at which an observation is made and that may influence it. In WIGOS, description is used to describe an observingFacility or Equipment. 
	"Validperiod" varchar(50) NULL,	-- Specifies at least the begin date of the indicated description. If omitted, the dateEstablished of the facility or deployedEquipment.validPeriod will be assumed.
	"DescriptionID" integer NOT NULL
)
;

CREATE TABLE "Equipment"
(
	"Driftperunittime" varchar(50) NULL,	-- 5-03 Intrinsic capability of the measurement/observing method - drift per unit time. Typically a percentage per unit time but could be absolute e.g. 1 deg per year.
	"Firmwareversion" varchar(50) NULL,	-- 5-09 Firmware version of the equipment
	"Manufacturer" varchar(50) NULL,	-- 5-09 Manufacturer of the equipment
	"Model" varchar(50) NULL,	-- 5-09 Model number of the equipment
	"Observablerange" varchar(50) NULL,	-- 5-03 Intrinsic capability of the measurement/observing method - range
	"Observingmethod" varchar(50) NULL,	-- 5-02 The method of measurement/observation used from the ObservingMethodType codelist.
	"Observingmethoddetails" varchar(50) NULL,	-- 5-02 A description of the method of measurement/observation used from the ObservingMethodType codelist. 
	"Serialnumber" varchar(50) NULL,	-- 5-09 Serial number of the equipment 
	"Specificationlink" varchar(50) NULL,	-- 5-03 Link to manufacturers (or other) specification describing the equipment.
	"Specifiedabsoluteuncertainty" varchar(50) NULL,	-- 5-03 Intrinsic capability of the measurement/observing method - specified absolute uncertainty e.g. 0.2 deg C (k=2).
	"Specifiedrelativeuncertainty" varchar(50) NULL,	-- 5-03 Intrinsic capability of the measurement/observing method - specified relative uncertainty. Typically a percentage.
	"Subequipment" varchar(50) NULL,
	"Uncertaintyevalproc" varchar(50) NULL,
	"EquipmentID" integer NOT NULL,
	"DeploymentID" integer NULL,
	facility integer NULL
)
;

CREATE TABLE "EquipmentEquipment"
(
	"subEquipment" integer NULL,
	"EquipmentID" integer NULL
)
;

CREATE TABLE "Equipmentlog"
(
	"EquipmentlogID" integer NOT NULL,
	equipment integer NULL
)
;

CREATE TABLE "Eventreport"
(
	"Typeofevent" varchar(50) NULL,	-- The type of event, taken from the EventType codelist (e.g. tree removal, storm damage etc).
	"Validperiod" varchar(50) NULL,
	"EventreportID" integer NOT NULL
)
;

CREATE TABLE "Facilitylog"
(
	"FacilitylogID" integer NOT NULL,
	facility integer NULL
)
;

CREATE TABLE "Facilityset"
(
	"FacilitysetID" integer NOT NULL
)
;

CREATE TABLE "FacilitySetObservingFacility"
(
	facility integer NULL,
	"facilitySet" integer NULL
)
;

CREATE TABLE "Frequencies"
(
	"Bandwidth" varchar(50) NULL,	-- The difference of the highest and the lowest frequency, expressed as a number with a unit of measure (uom). Expected values for gml attribute uom are: Hz, kHz, MHz, GHz, THz
	"Channel" varchar(50) NULL,	-- A name describing the frequency used
	"Frequency" varchar(50) NULL,	-- The nominal frequency used, expressed as a number with a unit of measure (uom). Expected values for gml attribute uom are: Hz, kHz, MHz, GHz, THz
	"Frequencyuse" varchar(50) NULL,	-- expected values are: Transmit, Receive, TransmitReceive
	"Polarization" varchar(50) NULL,
	"Purposeoffrequencyuse" varchar(50) NULL,	-- expected values are: observation, telecomms
	"Transmissionmode" varchar(50) NULL,	-- expected values are: pulsed, continuous use conditional on frequencyUse = Transmit
	"FrequenciesID" integer NOT NULL,
	"EquipmentID" integer NULL
)
;

CREATE TABLE "Geospatiallocation"
(
	"Coordinatereferencesystem" varchar(50) NULL,
	"Geolocation" varchar(50) NULL,	-- 3-07 Representative or conventional geospatial location of observing facility, the reference location. This will always be a point location, but this location can change with time.  5-12 Geospatial location of instrument or observing equipment, typically the location of the sensing element or sample inlet. This will always be a point location, but this location can change with time. 
	"Geopositioningmethod" varchar(50) NULL,	-- Element describes the method used to establish the specified geoLocation. [Codelist 11-01]
	"Validperiod" varchar(50) NULL,	-- The time period for which this geoLocation is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next geoLocation on record.
	"GeospatiallocationID" integer NOT NULL
)
;

CREATE TABLE "Header"
(
	"Filedatetime" timestamp without time zone NULL,	-- Date and time this file was last updated.
	"Recordowner" varchar(50) NULL,	-- The organisation responsible for the metadata.
	"Version" integer NULL,
	"HeaderID" integer NOT NULL
)
;

CREATE TABLE "Instrumentoperatingstatus"
(
	"Instrumentoperatingstatus" varchar(50) NULL,
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified instrumentOperatingStatus is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next instrumentOperatingStatus on record. If only one instrumentOperatingStatus is specified for an equipment, the time stamp is optional.
	"InstrumentoperatingstatusID" integer NOT NULL
)
;

CREATE TABLE "Log"
(
	"Logentry" varchar(50) NULL,	-- An entry in a Log. 
	"LogID" integer NOT NULL
)
;

CREATE TABLE "Logentry"
(
	"Author" varchar(50) NULL,	-- Author of the log entry.
	"Datetime" timestamp without time zone NULL,	-- Date and time of the event being logged
	"Description" varchar(50) NULL,	-- Description of the log entry
	"Documentationurl" varchar(50) NULL,	-- Link to additional documents, photos etc. about the event being logged.
	"LogentryID" integer NOT NULL
)
;

CREATE TABLE "Maintenancereport"
(
	"Maintenanceparty" varchar(50) NULL,	-- 5-11 Details of who performed the maintenance (individual or organisation).
	"MaintenancereportID" integer NOT NULL
)
;

CREATE TABLE "Observingcapability"
(
	"Observation" varchar(50) NULL,
	"Programaffiliation" varchar(50) NULL,
	"ObservingcapabilityID" integer NOT NULL,
	facility integer NULL
)
;

CREATE TABLE "Observingfacility"
(
	"Climatezone" varchar(50) NULL,	-- 4-07 type of climate zone at the facility. From the ClimateZoneType codelist.
	"Dateclosed" date NULL,
	"Dateestablished" date NULL,
	"Facilitytype" varchar(50) NULL,	-- 3-04 The type of the observing facility from the MonitoringFacilityType codelist.
	"Population" varchar(50) NULL,
	"Programaffiliation" varchar(50) NULL,	-- 2-02 The global, regional or national programme(s)/network(s) that the ObservingFacility is associated with. programAffiliation also enables the specification of a program-specific identifier of the ObservingFacility, an alias name,  the validPeriod of the programAffiliation, as well as the reportingStatus of an ObservingFacility under the respective program.
	"Surfacecover" varchar(50) NULL,	-- 4-01 The (bio)physical cover on the earth's surface in the vicinity of the observations from the LandCoverType codelist .  NOTE: Only applies for surface-based (fixed) observing facilities.
	"Surfaceroughness" varchar(50) NULL,	-- 4-06 surface roughness at the facility. From the SurfaceRoughnessType codelist.
	"Territory" varchar(50) NULL,	-- 3-02 The territory the observing facility is located in, from the TerritoryType codelist.
	"Timezone" varchar(50) NULL,	-- Time zone the observing facility is located in, from the timeZoneTypeType codelist.
	"Topographybathymetry" varchar(50) NULL,	-- 4-03 Topography or bathymetry characterizes the shape or configuration of a geographical feature, represented on a map by contour lines. It is implemented as a timestamped composite of four elements.
	"Wmoregion" varchar(50) NULL,	-- 3-01 The WMO region the observing facility is located in, from the WMORegionType codelist.
	"ObservingfacilityID" integer NOT NULL
)
;

CREATE TABLE "Population"
(
	"Population10km" integer NULL,	-- Population in a 10 km radius around the observing facility, specified in 1000s.
	"Population50km" integer NULL,	-- Population in a 50 km radius around the observing facility, specified in 1000s.
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.
	"PopulationID" integer NOT NULL
)
;

CREATE TABLE "Process"
(
	"Extension" varchar(50) NULL,	-- This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks. However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. 
	"ProcessID" integer NOT NULL
)
;

CREATE TABLE "Processing"
(
	"Aggregationperiod" varchar(50) NULL,	-- 7-09 Time period over which individual samples/observations are aggregated
	"Dataprocessing" varchar(50) NULL,	-- 7-01 A description of the data processing used to generate observations including, if relevant, algorithms used to derive the result.
	"Processingcentre" varchar(50) NULL,	-- 7-02 Center at which the observation is processed. Although this is a free text string, it is expected that in practice this value should be from a controlled list of known centers.
	"Softwaredetails" varchar(50) NULL,	-- 7-05 Name and version of the software or processor used to derive the values
	"Softwareurl" varchar(50) NULL,	-- 7-05 URL for the software or processor used to derive the values
	"ProcessingID" integer NOT NULL,
	"DatagenerationID" integer NULL
)
;

CREATE TABLE "Programaffiliation"
(
	"Programaffiliation" varchar(50) NULL,
	"Programspecificfacilityid" varchar(50) NULL,
	"Reportingstatus" varchar(50) NULL,
	"ProgramaffiliationID" integer NOT NULL
)
;

CREATE TABLE "Reporting"
(
	"Dataformat" varchar(50) NULL,	-- 7-07 Description of the format in which the observed variable is primarily being provided, from the DataFormatType codelist. 
	"Dataformatversion" varchar(50) NULL,	-- 7-08 Version of the data format.
	"Datapolicy" varchar(50) NULL,	-- 9-02 Details relating to the use and limitations surrounding data imposed by the supervising organization.
	"Internationalexchange" boolean NULL,
	"Levelofdata" varchar(50) NULL,	-- 7-06 Level of data processing
	"Numberofobservationsinreportinginterval" integer NULL,	-- Specifies how many aggregated observations are reported on average in each temporal reporting interval. For full temporal coverage, the number of observations reported = temporal reporting interval / aggregation period.
	"Numericalresolution" integer NULL,	-- 7-12 Numerical resolution is a measure of the detail to which a numerical quantity is expressed. This is synonymous to numerical precision of the reporting, but can be different than the numerical precision of the observed value.
	"Officialstatus" boolean NULL,	-- 5-14 Official status of observation.
	"Referencedatum" varchar(50) NULL,	-- 7-11 Reference datum used to convert observed quantity to reported quantity
	"Referencetimesource" varchar(50) NULL,	-- 7-10 Time reference used for observations.
	"Spatialreportinginterval" varchar(50) NULL,	-- 7-03 Spatial interval over which the observed variable is reported. Note that this is expressed as length, without geo-referencing. 
	"Temporalreportinginterval" varchar(50) NULL,	-- 7-03 Time interval over which the observed variable is reported. Note that this is a temporal distance, e.g., (every) 1 hour. 
	"Timeliness" varchar(50) NULL,	-- 7-13 Timeliness of reporting is the typical time taken between completion of the observation and when it becomes available to users.
	"Timestampmeaning" varchar(50) NULL,	-- 7-03 Meaning of the time stamp in the temporalReportingInterval taken from the TimeStampMeaning codelist.
	"Uom" varchar(50) NULL,	-- 1-02 Measurement Unit (unit of measure)
	"ReportingID" integer NOT NULL,
	"DatagenerationID" integer NULL
)
;

CREATE TABLE "Reportingstatus"
(
	"Reportingstatus" varchar(50) NULL,	-- 3-09 Declared reporting status of an observing facility [under a certain network/program affiliation]. 
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified reporting status is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next territory on record. If only one reporting status is specified for an observing facility, the time stamp is optional.
	"ReportingstatusID" integer NOT NULL
)
;

CREATE TABLE "Responsibleparty"
(
	"Responsibleparty" varchar(50) NULL,	-- 10-01 Party (organization or individual) responsible for the observing facility or equipment.
	"Validperiod" varchar(50) NULL,	-- The time period for which this responsibleParty is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next responsibleParty on record.
	"ResponsiblepartyID" integer NOT NULL
)
;

CREATE TABLE "Resultset"
(
	"Distributioninfo" varchar(50) NULL,	-- The distributionInfo provides information about how to source the data, described using MD_Distribution from ISO 19115.
	"ResultsetID" integer NOT NULL
)
;

CREATE TABLE "Sampling"
(
	"Samplespertimeperiod" integer NULL,
	"Sampletreatment" varchar(50) NULL,	-- 6-02 Description of chemical or physical treatment of the sample prior to analysis from the SampleTreatmentType codelist.
	"Samplingprocedure" varchar(50) NULL,	-- 6-01 The procedure(s) involved in obtaining a sample/making an observation. Taken from the SamplingProcedureType codelist
	"Samplingproceduredescription" varchar(50) NULL,	-- 6-01 Description of the procedure(s) involved in obtaining a sample/making an observation.
	"Samplingstrategy" varchar(50) NULL,	-- 6-03 The strategy used to generate the observed variable.
	"Samplingtimeperiod" varchar(50) NULL,	-- 6-04 The period of time over which a measurement is taken. This value is a duration, e.g. 1 hour, not specific times and dates. 
	"Spatialsamplingresolution" varchar(50) NULL,	-- 6-05 The spatial sampling resolution is the size of the smallest observable object. The value of this property may be supported by explanatory information in spatialSamplingResolutionDescription.
	"Spatialsamplingresolutiondetails" varchar(50) NULL,	-- 6-05 Explanatory information about the exact meaning of the value of samplingResolution. Note: not currently supported.
	"Temporalsamplinginterval" varchar(50) NULL,	-- 6-06 Time period (as a duration) between the beginning of consecutive sampling periods.
	"SamplingID" integer NOT NULL,
	"DatagenerationID" integer NULL
)
;

CREATE TABLE "Schedule"
(
	"Diurnalbasetime" time without time zone NULL,
	"Endhour" integer NULL,	-- End hour of schedule (0 to 23)
	"Endminute" integer NULL,	-- End minute of schedule (0 to 59)
	"Endmonth" integer NULL,	-- End month of schedule (January = 1, December = 12)
	"Endweekday" integer NULL,	-- End day of schedule (Monday = 1, Sunday = 7)
	"Starthour" integer NULL,	-- Start hour of schedule (0 to 23)
	"Startminute" integer NULL,	-- Start minute of schedule (0 to 59)
	"Startmonth" integer NULL,	-- Start month of schedule (January = 1, December = 12)
	"Startweekday" integer NULL,	-- Start day of schedule (Monday = 1, Sunday = 7)
	"ScheduleID" integer NOT NULL,
	"DatagenerationID" integer NULL
)
;

CREATE TABLE "Surfacecover"
(
	"Surfacecover" varchar(50) NULL,	-- 4-01 The (bio)physical cover on the earth's surface in the vicinity of the observations from the LandCoverType codelist .  NOTE: Only applies for surface-based (fixed) observing facilities.
	"Surfacecoverclassification" varchar(50) NULL,	-- 4-02 Reference to a surface cover classification type from the SurfaceCoverClassificationType codelist. NOTE: only if 4-01 is specified
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified surfaceCover is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next surfaceCover on record. If only one surfaceCover is specified for an observing facility, the time stamp is optional.
	"SurfacecoverID" integer NOT NULL
)
;

CREATE TABLE "Surfaceroughness"
(
	"Surfaceroughness" varchar(50) NULL,	-- 4-06 surface roughness at the facility. From the SurfaceRoughnessType codelist.
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified surfaceRoughness is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next surfaceRoughness on record. If only one surfaceRoughness is specified for an observing facility, the time stamp is optional.
	"SurfaceroughnessID" integer NOT NULL
)
;

CREATE TABLE "Territory"
(
	"Territoryname" varchar(50) NULL,	-- 3-02 The territory the observing facility is located in, from the TerritoryType codelist.
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified territory is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next territory on record. If only one territory is specified for an observing facility, the time stamp is optional.
	"TerritoryID" integer NOT NULL
)
;

CREATE TABLE "Timezone"
(
	"Timezone" varchar(50) NULL,	-- Time zone of the observing facility
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.
	"TimezoneID" integer NOT NULL
)
;

CREATE TABLE "Topographybathymetry"
(
	"Altitudeordepth" varchar(50) NULL,	-- 4-03 The altitude/depth with respect to mean sea level from the AltitudeOrDepthTypeCodelist
	"Localtopography" varchar(50) NULL,	-- 4-03 The local topography from the LocalTopographyType codelist
	"Relativeelevation" varchar(50) NULL,	-- 4-03 The relative elevation from the RelativeElevationType codelist
	"Topographiccontext" varchar(50) NULL,	-- 4-03 The topographic context from the TopographicContextType codelist
	"Validperiod" varchar(50) NULL,	-- The time period for which the specified topographyBathymetry is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next topographyBathymetry on record. If only one topographyBathymetry is specified for an observing facility, the time stamp is optional.
	"TopographybathymetryID" integer NOT NULL
)
;

CREATE TABLE "Wigosmetadatarecord"
(
	"Deployment" varchar(50) NULL,	-- A Deployment instance in this record. Note that Deployments may also be encoded inline with the OM_Observation (as part of the Process).
	"Equipment" varchar(50) NULL,	-- An Equipment instance in this metadata record.
	"Equipmentlog" varchar(50) NULL,	-- An EquipmentLog instance in this metadata record. Note that an EquipmentLog may also be encoded inline with the Equipment instance.
	"Extension" varchar(50) NULL,	-- This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks. However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. 
	"Facility" varchar(50) NULL,	-- An ObservingFacility instance in this metadata record.
	"Facilitylog" varchar(50) NULL,	-- A FacilityLog instance in this metadata record. Note that an FacilityLog may also be encoded inline with the ObservingFacility instance.
	"Facilityset" varchar(50) NULL,	-- A FacilitySet instance in this metadata record. The FacilitySet will simply consist of links to ObservingFacilities belonging to the set.
	"Headerinformation" varchar(50) NULL,	-- A header section must be included with every WIGOS MetadataRecord.
	"Observation" varchar(50) NULL,
	"WigosmetadatarecordID" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Abstractenvironmentalmonitoringfacility" ADD CONSTRAINT "PK_Abstractenvironmentalmonitoringfacility"
	PRIMARY KEY ("AbstractenvironmentalmonitoringfacilityID")
;

ALTER TABLE "Attribution" ADD CONSTRAINT "PK_Attribution"
	PRIMARY KEY ("AttributionID")
;

ALTER TABLE "Climatezone" ADD CONSTRAINT "PK_Climatezone"
	PRIMARY KEY ("ClimatezoneID")
;

ALTER TABLE "Controlcheckreport" ADD CONSTRAINT "PK_Controlcheckreport"
	PRIMARY KEY ("ControlcheckreportID")
;

ALTER TABLE "Datageneration" ADD CONSTRAINT "PK_Datageneration"
	PRIMARY KEY ("DatagenerationID")
;

ALTER TABLE "Datapolicy" ADD CONSTRAINT "PK_Datapolicy"
	PRIMARY KEY ("DatapolicyID")
;

ALTER TABLE "Deployment" ADD CONSTRAINT "PK_Deployment"
	PRIMARY KEY ("DeploymentID")
;

ALTER TABLE "Description" ADD CONSTRAINT "PK_Description"
	PRIMARY KEY ("DescriptionID")
;

ALTER TABLE "Equipment" ADD CONSTRAINT "PK_Equipment"
	PRIMARY KEY ("EquipmentID")
;

ALTER TABLE "Equipmentlog" ADD CONSTRAINT "PK_Equipmentlog"
	PRIMARY KEY ("EquipmentlogID")
;

ALTER TABLE "Eventreport" ADD CONSTRAINT "PK_Eventreport"
	PRIMARY KEY ("EventreportID")
;

ALTER TABLE "Facilitylog" ADD CONSTRAINT "PK_Facilitylog"
	PRIMARY KEY ("FacilitylogID")
;

ALTER TABLE "Facilityset" ADD CONSTRAINT "PK_Facilityset"
	PRIMARY KEY ("FacilitysetID")
;

ALTER TABLE "Frequencies" ADD CONSTRAINT "PK_Frequencies"
	PRIMARY KEY ("FrequenciesID")
;

ALTER TABLE "Geospatiallocation" ADD CONSTRAINT "PK_Geospatiallocation"
	PRIMARY KEY ("GeospatiallocationID")
;

ALTER TABLE "Header" ADD CONSTRAINT "PK_Header"
	PRIMARY KEY ("HeaderID")
;

ALTER TABLE "Instrumentoperatingstatus" ADD CONSTRAINT "PK_Instrumentoperatingstatus"
	PRIMARY KEY ("InstrumentoperatingstatusID")
;

ALTER TABLE "Log" ADD CONSTRAINT "PK_Log"
	PRIMARY KEY ("LogID")
;

ALTER TABLE "Logentry" ADD CONSTRAINT "PK_Logentry"
	PRIMARY KEY ("LogentryID")
;

ALTER TABLE "Maintenancereport" ADD CONSTRAINT "PK_Maintenancereport"
	PRIMARY KEY ("MaintenancereportID")
;

ALTER TABLE "Observingcapability" ADD CONSTRAINT "PK_Observingcapability"
	PRIMARY KEY ("ObservingcapabilityID")
;

ALTER TABLE "Observingfacility" ADD CONSTRAINT "PK_Observingfacility"
	PRIMARY KEY ("ObservingfacilityID")
;

ALTER TABLE "Population" ADD CONSTRAINT "PK_Population"
	PRIMARY KEY ("PopulationID")
;

ALTER TABLE "Process" ADD CONSTRAINT "PK_Process"
	PRIMARY KEY ("ProcessID")
;

ALTER TABLE "Processing" ADD CONSTRAINT "PK_Processing"
	PRIMARY KEY ("ProcessingID")
;

ALTER TABLE "Programaffiliation" ADD CONSTRAINT "PK_Programaffiliation"
	PRIMARY KEY ("ProgramaffiliationID")
;

ALTER TABLE "Reporting" ADD CONSTRAINT "PK_Reporting"
	PRIMARY KEY ("ReportingID")
;

ALTER TABLE "Reportingstatus" ADD CONSTRAINT "PK_Reportingstatus"
	PRIMARY KEY ("ReportingstatusID")
;

ALTER TABLE "Responsibleparty" ADD CONSTRAINT "PK_Responsibleparty"
	PRIMARY KEY ("ResponsiblepartyID")
;

ALTER TABLE "Resultset" ADD CONSTRAINT "PK_Resultset"
	PRIMARY KEY ("ResultsetID")
;

ALTER TABLE "Sampling" ADD CONSTRAINT "PK_Sampling"
	PRIMARY KEY ("SamplingID")
;

ALTER TABLE "Schedule" ADD CONSTRAINT "PK_Schedule"
	PRIMARY KEY ("ScheduleID")
;

ALTER TABLE "Surfacecover" ADD CONSTRAINT "PK_Surfacecover"
	PRIMARY KEY ("SurfacecoverID")
;

ALTER TABLE "Surfaceroughness" ADD CONSTRAINT "PK_Surfaceroughness"
	PRIMARY KEY ("SurfaceroughnessID")
;

ALTER TABLE "Territory" ADD CONSTRAINT "PK_Territory"
	PRIMARY KEY ("TerritoryID")
;

ALTER TABLE "Timezone" ADD CONSTRAINT "PK_Timezone"
	PRIMARY KEY ("TimezoneID")
;

ALTER TABLE "Topographybathymetry" ADD CONSTRAINT "PK_Topographybathymetry"
	PRIMARY KEY ("TopographybathymetryID")
;

ALTER TABLE "Wigosmetadatarecord" ADD CONSTRAINT "PK_Wigosmetadatarecord"
	PRIMARY KEY ("WigosmetadatarecordID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Controlcheckreport" ADD CONSTRAINT "FK_ControlCheckReport_LogEntry"
	FOREIGN KEY ("ControlcheckreportID") REFERENCES "Logentry" ("LogentryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datageneration" ADD CONSTRAINT "FK_DataGeneration_dataGeneration"
	FOREIGN KEY ("DeploymentID") REFERENCES "Deployment" ("DeploymentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Deployment" ADD CONSTRAINT "FK_Deployment_deployment"
	FOREIGN KEY ("ProcessID") REFERENCES "Process" ("ProcessID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Equipment" ADD CONSTRAINT "FK_Equipment_AbstractEnvironmentalMonitoringFacility"
	FOREIGN KEY ("EquipmentID") REFERENCES "Abstractenvironmentalmonitoringfacility" ("AbstractenvironmentalmonitoringfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Equipment" ADD CONSTRAINT "FK_Equipment_deployedEquipment"
	FOREIGN KEY ("DeploymentID") REFERENCES "Deployment" ("DeploymentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Equipment" ADD CONSTRAINT "FK_Equipment_equipment"
	FOREIGN KEY (facility) REFERENCES "Observingfacility" ("ObservingfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "EquipmentEquipment" ADD CONSTRAINT "FK_EquipmentEquipment_subEquipment"
	FOREIGN KEY ("subEquipment") REFERENCES "Equipment" ("EquipmentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "EquipmentEquipment" ADD CONSTRAINT "FK_EquipmentEquipment_Equipment"
	FOREIGN KEY ("EquipmentID") REFERENCES "Equipment" ("EquipmentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Equipmentlog" ADD CONSTRAINT "FK_EquipmentLog_equipmentLog"
	FOREIGN KEY (equipment) REFERENCES "Equipment" ("EquipmentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Equipmentlog" ADD CONSTRAINT "FK_EquipmentLog_Log"
	FOREIGN KEY ("EquipmentlogID") REFERENCES "Log" ("LogID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Eventreport" ADD CONSTRAINT "FK_EventReport_LogEntry"
	FOREIGN KEY ("EventreportID") REFERENCES "Logentry" ("LogentryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Facilitylog" ADD CONSTRAINT "FK_FacilityLog_Log"
	FOREIGN KEY ("FacilitylogID") REFERENCES "Log" ("LogID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Facilitylog" ADD CONSTRAINT "FK_FacilityLog_facilityLog"
	FOREIGN KEY (facility) REFERENCES "Observingfacility" ("ObservingfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FacilitySetObservingFacility" ADD CONSTRAINT "FK_FacilitySetObservingFacility_facility"
	FOREIGN KEY (facility) REFERENCES "Observingfacility" ("ObservingfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FacilitySetObservingFacility" ADD CONSTRAINT "FK_FacilitySetObservingFacility_facilitySet"
	FOREIGN KEY ("facilitySet") REFERENCES "Facilityset" ("FacilitysetID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Frequencies" ADD CONSTRAINT "FK_Frequencies_Equipment"
	FOREIGN KEY ("EquipmentID") REFERENCES "Equipment" ("EquipmentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Maintenancereport" ADD CONSTRAINT "FK_MaintenanceReport_LogEntry"
	FOREIGN KEY ("MaintenancereportID") REFERENCES "Logentry" ("LogentryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Observingcapability" ADD CONSTRAINT "FK_ObservingCapability_facility"
	FOREIGN KEY (facility) REFERENCES "Observingfacility" ("ObservingfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Observingfacility" ADD CONSTRAINT "FK_ObservingFacility_AbstractEnvironmentalMonitoringFacility"
	FOREIGN KEY ("ObservingfacilityID") REFERENCES "Abstractenvironmentalmonitoringfacility" ("AbstractenvironmentalmonitoringfacilityID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Processing" ADD CONSTRAINT "FK_Processing_processing"
	FOREIGN KEY ("DatagenerationID") REFERENCES "Datageneration" ("DatagenerationID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Reporting" ADD CONSTRAINT "FK_Reporting_reporting"
	FOREIGN KEY ("DatagenerationID") REFERENCES "Datageneration" ("DatagenerationID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Sampling" ADD CONSTRAINT "FK_Sampling_sampling"
	FOREIGN KEY ("DatagenerationID") REFERENCES "Datageneration" ("DatagenerationID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Schedule" ADD CONSTRAINT "FK_Schedule_schedule"
	FOREIGN KEY ("DatagenerationID") REFERENCES "Datageneration" ("DatagenerationID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Abstractenvironmentalmonitoringfacility"
	IS 'An abstract class for environmental monitoring facilities. An environmental monitoring facility may be a station, a platform (moving or stationary), or it may be a sensor or an instrument. WIGOS defines two concrete specialisations: ObservingFacility (to represent stations/platforms) and Equipment (to represent sensors/instruments). NOTE: The WIGOS specialisations of AbstractEnvironmentalMonitoringFacility (ObservingFacility, Equipment) can both be mapped conceptually to the INSPIRE EF EnvironmentalMonitoringFacility.'
;

COMMENT ON COLUMN "Abstractenvironmentalmonitoringfacility"."Description"
	IS '4-05 Non-formalized information about the location and surroundings at which an observation is made and that may influence it. In WIGOS, description is used to describe an observingFacility or Equipment. '
;

COMMENT ON COLUMN "Abstractenvironmentalmonitoringfacility"."Extension"
	IS 'This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks.
However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. '
;

COMMENT ON COLUMN "Abstractenvironmentalmonitoringfacility"."Geospatiallocation"
	IS '3-07 Position in space defining the location of the environmental monitoring station/platform at the time of observation.

5-12 Geospatial location of instrument/sensor'
;

COMMENT ON COLUMN "Abstractenvironmentalmonitoringfacility"."Onlineresource"
	IS 'An online resource containing additional information about the facility or equipment'
;

COMMENT ON COLUMN "Abstractenvironmentalmonitoringfacility"."Responsibleparty"
	IS 'The organisation responsible.'
;

COMMENT ON COLUMN "Attribution"."Originator"
	IS 'Identifies the individual and/or organization at the origin of the resource. This is typically the owner of the ressource, e.g., a data set.'
;

COMMENT ON COLUMN "Attribution"."Title"
	IS 'The title of the attributed work.'
;

COMMENT ON TABLE "Climatezone"
	IS 'A ClimateZone is a climateZone specification accompanied by a timestamp indicating the time from which that climateZone is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple climateZone which are valid over different consecutive periods of time. If only a single climateZone is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Climatezone"."Climatezone"
	IS '4-07 type of climate zone at the facility. From the ClimateZoneType codelist.'
;

COMMENT ON COLUMN "Climatezone"."Validperiod"
	IS 'The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Controlcheckreport"
	IS 'A ControlCheckReport describes a calibration type event. E.g. instrument was re-calibrated.'
;

COMMENT ON COLUMN "Controlcheckreport"."Alternateuri"
	IS '5-08 Alternatively the summary of the control check may be provided via a URI that resolves to a document containing this information.'
;

COMMENT ON COLUMN "Controlcheckreport"."Checklocation"
	IS '5-08 Location of sensor when check was performed (e.g. in-situ, offsite etc.) From codelist ControlCheckLocationType.'
;

COMMENT ON COLUMN "Controlcheckreport"."Controlcheckresult"
	IS '5-08 Result of the control check, from InstrumentControlResultType codelist'
;

COMMENT ON COLUMN "Controlcheckreport"."Periodofvalidity"
	IS '5-08 period of validity of the control check (e.g. 4 years)'
;

COMMENT ON COLUMN "Controlcheckreport"."Standardname"
	IS '5-08 Nameof the Standard used.'
;

COMMENT ON COLUMN "Controlcheckreport"."Standardserialnumber"
	IS '5-08 Serial Number of the standard used.'
;

COMMENT ON COLUMN "Controlcheckreport"."Standardtype"
	IS '5-08 Type of the Standard used. From the StandardType code list.'
;

COMMENT ON COLUMN "Controlcheckreport"."Withinverificationlimit"
	IS '5-08 Was the instrument found to be within verification limits (True if yes, False if no)'
;

COMMENT ON COLUMN "Datageneration"."Validperiod"
	IS 'The period of time for which this processing arrangement was/is in place. (Note: this time period must fall within the time period specified in the Deployment).'
;

COMMENT ON COLUMN "Datapolicy"."Attribution"
	IS 'Describes the attribution details pertinent to dataPolicy'
;

COMMENT ON COLUMN "Datapolicy"."Datapolicy"
	IS '9-02 Details relating to the use and limitations surrounding data imposed by the supervising organization.'
;

COMMENT ON TABLE "Deployment"
	IS 'The deployment(s) describe which equipment is deployed, during which time period, and in which configuration in the course of generating observations. A Deployment can describe any period of time (equipment could be deployed for less than a day, e.g. a mobile sensor deployed in the field, or it could be deployed for many years.) A defining characteristic of the Deployment is that the configuration described in the Deployment remains, by-and-large, unchanged for the duration of the deployment. If the configuration changes, then a new Deployment must be recorded.'
;

COMMENT ON COLUMN "Deployment"."Applicationarea"
	IS '2-01 The context within, or intended application(s) for which the observation is primarily made or which has/have the most stringent requirements.'
;

COMMENT ON COLUMN "Deployment"."Communicationmethod"
	IS '3-08 The primary data communication method, from the DataCommunicationMethodType codelist.'
;

COMMENT ON COLUMN "Deployment"."Configuration"
	IS '5-06 Description of any shielding or configuration/setup of the instrumentation.'
;

COMMENT ON COLUMN "Deployment"."Controlschedule"
	IS '5-07 Description of schedule for calibrations or verification of instrument.'
;

COMMENT ON COLUMN "Deployment"."Exposure"
	IS '5-15 The degree to which an instrument is affected by external influences according to the CIMO classification. Value from ExposureType codelist.'
;

COMMENT ON COLUMN "Deployment"."Heightabovelocalreferencesurface"
	IS '5-05 Vertical distance of sensor from specified reference surface, in the direction away from the earth''s center. Positive values indicate above reference surface, negative values indicate below references surface (e.g., below ocean surface).'
;

COMMENT ON COLUMN "Deployment"."Instrumentoperatingstatus"
	IS '5-04 The operational status of the instrument when deployed (Operational, testing etc.).'
;

COMMENT ON COLUMN "Deployment"."Localreferencesurface"
	IS '5-05 Description of the specified reference surface taken from the codelist LocalReferenceSurfaceType'
;

COMMENT ON COLUMN "Deployment"."Maintenanceschedule"
	IS '5-10 A description (and schedule) of maintenance that is routinely performed on an instrument'
;

COMMENT ON COLUMN "Deployment"."Representativeness"
	IS '1-05 An assessment of the representativeness of the observations from the RepresentativenessType codelist.'
;

COMMENT ON COLUMN "Deployment"."Sourceofobservation"
	IS '5-01 The source of the observation (manual, automatic, visual etc.) from the SourceOfObservationType codelist.'
;

COMMENT ON COLUMN "Deployment"."Validperiod"
	IS 'The period of time for which this deployment configuration was/is in place. (Note: this time period must fall within the time period specified in the OM_Observation phenomenonTime)'
;

COMMENT ON TABLE "Description"
	IS 'A Description is a description accompanied by a timestamp indicating the time from which that description is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility or Equipment may carry multiple descriptions which are valid over different periods of time.'
;

COMMENT ON COLUMN "Description"."Description"
	IS '4-05 Non-formalized information about the location and surroundings at which an observation is made and that may influence it. In WIGOS, description is used to describe an observingFacility or Equipment. '
;

COMMENT ON COLUMN "Description"."Validperiod"
	IS 'Specifies at least the begin date of the indicated description. If omitted, the dateEstablished of the facility or deployedEquipment.validPeriod will be assumed.'
;

COMMENT ON TABLE "Equipment"
	IS 'Equipment or instrument used to make observations.'
;

COMMENT ON COLUMN "Equipment"."Driftperunittime"
	IS '5-03 Intrinsic capability of the measurement/observing method - drift per unit time. Typically a percentage per unit time but could be absolute e.g. 1 deg per year.'
;

COMMENT ON COLUMN "Equipment"."Firmwareversion"
	IS '5-09 Firmware version of the equipment'
;

COMMENT ON COLUMN "Equipment"."Manufacturer"
	IS '5-09 Manufacturer of the equipment'
;

COMMENT ON COLUMN "Equipment"."Model"
	IS '5-09 Model number of the equipment'
;

COMMENT ON COLUMN "Equipment"."Observablerange"
	IS '5-03 Intrinsic capability of the measurement/observing method - range'
;

COMMENT ON COLUMN "Equipment"."Observingmethod"
	IS '5-02 The method of measurement/observation used from the ObservingMethodType codelist.'
;

COMMENT ON COLUMN "Equipment"."Observingmethoddetails"
	IS '5-02 A description of the method of measurement/observation used from the ObservingMethodType codelist. '
;

COMMENT ON COLUMN "Equipment"."Serialnumber"
	IS '5-09 Serial number of the equipment '
;

COMMENT ON COLUMN "Equipment"."Specificationlink"
	IS '5-03 Link to manufacturers (or other) specification describing the equipment.'
;

COMMENT ON COLUMN "Equipment"."Specifiedabsoluteuncertainty"
	IS '5-03 Intrinsic capability of the measurement/observing method - specified absolute uncertainty e.g. 0.2 deg C (k=2).'
;

COMMENT ON COLUMN "Equipment"."Specifiedrelativeuncertainty"
	IS '5-03 Intrinsic capability of the measurement/observing method - specified relative uncertainty. Typically a percentage.'
;

COMMENT ON TABLE "Equipmentlog"
	IS '5-13 The EquipmentLog is used to capture notable events and extra information about the equipment used to obtain the observations, such as actual maintenance performed on the instrument.'
;

COMMENT ON COLUMN "Eventreport"."Typeofevent"
	IS 'The type of event, taken from the EventType codelist (e.g. tree removal, storm damage etc).'
;

COMMENT ON TABLE "Facilitylog"
	IS '4-04 The FacilityLog is used to capture notable events and extra information about the observing facility or its surroundings. '
;

COMMENT ON TABLE "Facilityset"
	IS 'A set of associated ObservingFacilities. Association (grouping) criteria can vary and maybe program/network specific. Examples: In GAW, some Global stations consist of several distinct observing facilities; The NASA A-Train may be considered a FacilitySet comprised of several individual satellites.'
;

COMMENT ON COLUMN "Frequencies"."Bandwidth"
	IS 'The difference of the highest and the lowest frequency, expressed as a number with a unit of measure (uom). Expected values for gml attribute uom are: Hz, kHz, MHz, GHz, THz'
;

COMMENT ON COLUMN "Frequencies"."Channel"
	IS 'A name describing the frequency used'
;

COMMENT ON COLUMN "Frequencies"."Frequency"
	IS 'The nominal frequency used, expressed as a number with a unit of measure (uom). Expected values for gml attribute uom are: Hz, kHz, MHz, GHz, THz'
;

COMMENT ON COLUMN "Frequencies"."Frequencyuse"
	IS 'expected values are: Transmit, Receive, TransmitReceive'
;

COMMENT ON COLUMN "Frequencies"."Purposeoffrequencyuse"
	IS 'expected values are: observation, telecomms'
;

COMMENT ON COLUMN "Frequencies"."Transmissionmode"
	IS 'expected values are: pulsed, continuous
use conditional on frequencyUse = Transmit'
;

COMMENT ON TABLE "Geospatiallocation"
	IS 'A GeospatialLocation is a geospatial location accompanied by a timestamp indicating the time from which that location is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility or Equipment may carry multiple locations which are valid over different periods of time.'
;

COMMENT ON COLUMN "Geospatiallocation"."Geolocation"
	IS '3-07 Representative or conventional geospatial location of observing facility, the reference location. This will always be a point location, but this location can change with time.

5-12 Geospatial location of instrument or observing equipment, typically the location of the sensing element or sample inlet. This will always be a point location, but this location can change with time. '
;

COMMENT ON COLUMN "Geospatiallocation"."Geopositioningmethod"
	IS 'Element describes the method used to establish the specified geoLocation. [Codelist 11-01]'
;

COMMENT ON COLUMN "Geospatiallocation"."Validperiod"
	IS 'The time period for which this geoLocation is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next geoLocation on record.'
;

COMMENT ON TABLE "Header"
	IS 'Header contains header information about a WIGOSMetadataRecord. This is metadata about the record used to facilitate transport or ingestion into a system such as OSCAR.'
;

COMMENT ON COLUMN "Header"."Filedatetime"
	IS 'Date and time this file was last updated.'
;

COMMENT ON COLUMN "Header"."Recordowner"
	IS 'The organisation responsible for the metadata.'
;

COMMENT ON COLUMN "Instrumentoperatingstatus"."Validperiod"
	IS 'The time period for which the specified instrumentOperatingStatus is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next instrumentOperatingStatus on record. If only one instrumentOperatingStatus is specified for an equipment, the time stamp is optional.'
;

COMMENT ON TABLE "Log"
	IS 'At the abstract level a log is simply a record of log entries. The requirements for a log may depend on the type of log it is therefore specialized logs exist for specific types of log (such as ControlCheckReports, MaintenanceReports and EventReports).'
;

COMMENT ON COLUMN "Log"."Logentry"
	IS 'An entry in a Log. '
;

COMMENT ON TABLE "Logentry"
	IS 'At the abstract level a log entry contains the time, author and descriptions of the activity or event being logged. This class is specialized further to provide more specific log entry types where needed. '
;

COMMENT ON COLUMN "Logentry"."Author"
	IS 'Author of the log entry.'
;

COMMENT ON COLUMN "Logentry"."Datetime"
	IS 'Date and time of the event being logged'
;

COMMENT ON COLUMN "Logentry"."Description"
	IS 'Description of the log entry'
;

COMMENT ON COLUMN "Logentry"."Documentationurl"
	IS 'Link to additional documents, photos etc. about the event being logged.'
;

COMMENT ON TABLE "Maintenancereport"
	IS '5-13 Description of maintenance (actual) performed on instrument.'
;

COMMENT ON COLUMN "Maintenancereport"."Maintenanceparty"
	IS '5-11 Details of who performed the maintenance (individual or organisation).'
;

COMMENT ON TABLE "Observingfacility"
	IS '[WMDS Category 3] An observing facility (station/platform) can be anything that supports making observations, e.g., a fixed station, moving equipment or a remote sensing platform. In abstract terms, an observing facility groups a near colocation of observing equipment managed by a single entity or several entities.'
;

COMMENT ON COLUMN "Observingfacility"."Climatezone"
	IS '4-07 type of climate zone at the facility. From the ClimateZoneType codelist.'
;

COMMENT ON COLUMN "Observingfacility"."Facilitytype"
	IS '3-04 The type of the observing facility from the MonitoringFacilityType codelist.'
;

COMMENT ON COLUMN "Observingfacility"."Programaffiliation"
	IS '2-02 The global, regional or national programme(s)/network(s) that the ObservingFacility is associated with. programAffiliation also enables the specification of a program-specific identifier of the ObservingFacility, an alias name,  the validPeriod of the programAffiliation, as well as the reportingStatus of an ObservingFacility under the respective program.'
;

COMMENT ON COLUMN "Observingfacility"."Surfacecover"
	IS '4-01 The (bio)physical cover on the earth''s surface in the vicinity of the observations from the LandCoverType codelist . 
NOTE: Only applies for surface-based (fixed) observing facilities.'
;

COMMENT ON COLUMN "Observingfacility"."Surfaceroughness"
	IS '4-06 surface roughness at the facility. From the SurfaceRoughnessType codelist.'
;

COMMENT ON COLUMN "Observingfacility"."Territory"
	IS '3-02 The territory the observing facility is located in, from the TerritoryType codelist.'
;

COMMENT ON COLUMN "Observingfacility"."Timezone"
	IS 'Time zone the observing facility is located in, from the timeZoneTypeType codelist.'
;

COMMENT ON COLUMN "Observingfacility"."Topographybathymetry"
	IS '4-03 Topography or bathymetry characterizes the shape or configuration of a geographical feature, represented on a map by contour lines. It is implemented as a timestamped composite of four elements.'
;

COMMENT ON COLUMN "Observingfacility"."Wmoregion"
	IS '3-01 The WMO region the observing facility is located in, from the WMORegionType codelist.'
;

COMMENT ON TABLE "Population"
	IS 'A Population is a population specification accompanied by a timestamp indicating the time from which that population is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple population specifications which are valid over different consecutive periods of time. If only a single population is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Population"."Population10km"
	IS 'Population in a 10 km radius around the observing facility, specified in 1000s.'
;

COMMENT ON COLUMN "Population"."Population50km"
	IS 'Population in a 50 km radius around the observing facility, specified in 1000s.'
;

COMMENT ON COLUMN "Population"."Validperiod"
	IS 'The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Process"
	IS 'Details of the process used in the observation'
;

COMMENT ON COLUMN "Process"."Extension"
	IS 'This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks.
However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. '
;

COMMENT ON TABLE "Processing"
	IS '[WMDS Category 7] Details of the processing procedures including analysis and post-processing.'
;

COMMENT ON COLUMN "Processing"."Aggregationperiod"
	IS '7-09 Time period over which individual samples/observations are aggregated'
;

COMMENT ON COLUMN "Processing"."Dataprocessing"
	IS '7-01 A description of the data processing used to generate observations including, if relevant, algorithms used to derive the result.'
;

COMMENT ON COLUMN "Processing"."Processingcentre"
	IS '7-02 Center at which the observation is processed. Although this is a free text string, it is expected that in practice this value should be from a controlled list of known centers.'
;

COMMENT ON COLUMN "Processing"."Softwaredetails"
	IS '7-05 Name and version of the software or processor used to derive the values'
;

COMMENT ON COLUMN "Processing"."Softwareurl"
	IS '7-05 URL for the software or processor used to derive the values'
;

COMMENT ON TABLE "Reporting"
	IS '[WMDS Category 7] Details of the reporting procedures.'
;

COMMENT ON COLUMN "Reporting"."Dataformat"
	IS '7-07 Description of the format in which the observed variable is primarily being provided, from the DataFormatType codelist. '
;

COMMENT ON COLUMN "Reporting"."Dataformatversion"
	IS '7-08 Version of the data format.'
;

COMMENT ON COLUMN "Reporting"."Datapolicy"
	IS '9-02 Details relating to the use and limitations surrounding data imposed by the supervising organization.'
;

COMMENT ON COLUMN "Reporting"."Levelofdata"
	IS '7-06 Level of data processing'
;

COMMENT ON COLUMN "Reporting"."Numberofobservationsinreportinginterval"
	IS 'Specifies how many aggregated observations are reported on average in each temporal reporting interval. For full temporal coverage, the number of observations reported = temporal reporting interval / aggregation period.'
;

COMMENT ON COLUMN "Reporting"."Numericalresolution"
	IS '7-12 Numerical resolution is a measure of the detail to which a numerical quantity is expressed. This is synonymous to numerical precision of the reporting, but can be different than the numerical precision of the observed value.'
;

COMMENT ON COLUMN "Reporting"."Officialstatus"
	IS '5-14 Official status of observation.'
;

COMMENT ON COLUMN "Reporting"."Referencedatum"
	IS '7-11 Reference datum used to convert observed quantity to reported quantity'
;

COMMENT ON COLUMN "Reporting"."Referencetimesource"
	IS '7-10 Time reference used for observations.'
;

COMMENT ON COLUMN "Reporting"."Spatialreportinginterval"
	IS '7-03 Spatial interval over which the observed variable is reported. Note that this is expressed as length, without geo-referencing. '
;

COMMENT ON COLUMN "Reporting"."Temporalreportinginterval"
	IS '7-03 Time interval over which the observed variable is reported. Note that this is a temporal distance, e.g., (every) 1 hour. '
;

COMMENT ON COLUMN "Reporting"."Timeliness"
	IS '7-13 Timeliness of reporting is the typical time taken between completion of the observation and when it becomes available to users.'
;

COMMENT ON COLUMN "Reporting"."Timestampmeaning"
	IS '7-03 Meaning of the time stamp in the temporalReportingInterval taken from the TimeStampMeaning codelist.'
;

COMMENT ON COLUMN "Reporting"."Uom"
	IS '1-02 Measurement Unit (unit of measure)'
;

COMMENT ON TABLE "Reportingstatus"
	IS 'A ReportingStatus is a reporting / operational status of an observing facility accompanied by a timestamp indicating the time from which that status is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple reporting statuses which are valid over different consecutive periods of time. If only a single reporting status is specified, the timestamp is optional and is inferred from the dateEstablished.'
;

COMMENT ON COLUMN "Reportingstatus"."Reportingstatus"
	IS '3-09 Declared reporting status of an observing facility [under a certain network/program affiliation]. '
;

COMMENT ON COLUMN "Reportingstatus"."Validperiod"
	IS 'The time period for which the specified reporting status is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next territory on record. If only one reporting status is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Responsibleparty"
	IS 'A ResponsibleParty is an individual or organization accompanied by a timestamp indicating the time from which that responsibleParty is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility or Equipment may carry multiple responsibleParty which are valid over different periods of time.'
;

COMMENT ON COLUMN "Responsibleparty"."Responsibleparty"
	IS '10-01 Party (organization or individual) responsible for the observing facility or equipment.'
;

COMMENT ON COLUMN "Responsibleparty"."Validperiod"
	IS 'The time period for which this responsibleParty is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next responsibleParty on record.'
;

COMMENT ON TABLE "Resultset"
	IS 'The ResultSet contains distribution information for the observation result(s). This may contain direct links to the data or to services or websites where the data can be sourced. Each MD_Distribution shall use CI_OnlineResource to point to URLs where data can be found. In order to distinguish the different URLs in a ResultSet. the description property of each MD_Distribution shall be used do describe what the URL resolves to (near real time data, archive etc.)'
;

COMMENT ON COLUMN "Resultset"."Distributioninfo"
	IS 'The distributionInfo provides information about how to source the data, described using MD_Distribution from ISO 19115.'
;

COMMENT ON TABLE "Sampling"
	IS '6-01 Description of the procedure(s) involved in obtaining a sample/making an observation.'
;

COMMENT ON COLUMN "Sampling"."Sampletreatment"
	IS '6-02 Description of chemical or physical treatment of the sample prior to analysis from the SampleTreatmentType codelist.'
;

COMMENT ON COLUMN "Sampling"."Samplingprocedure"
	IS '6-01 The procedure(s) involved in obtaining a sample/making an observation. Taken from the SamplingProcedureType codelist'
;

COMMENT ON COLUMN "Sampling"."Samplingproceduredescription"
	IS '6-01 Description of the procedure(s) involved in obtaining a sample/making an observation.'
;

COMMENT ON COLUMN "Sampling"."Samplingstrategy"
	IS '6-03 The strategy used to generate the observed variable.'
;

COMMENT ON COLUMN "Sampling"."Samplingtimeperiod"
	IS '6-04 The period of time over which a measurement is taken. This value is a duration, e.g. 1 hour, not specific times and dates. '
;

COMMENT ON COLUMN "Sampling"."Spatialsamplingresolution"
	IS '6-05 The spatial sampling resolution is the size of the smallest observable object. The value of this property may be supported by explanatory information in spatialSamplingResolutionDescription.'
;

COMMENT ON COLUMN "Sampling"."Spatialsamplingresolutiondetails"
	IS '6-05 Explanatory information about the exact meaning of the value of samplingResolution. Note: not currently supported.'
;

COMMENT ON COLUMN "Sampling"."Temporalsamplinginterval"
	IS '6-06 Time period (as a duration) between the beginning of consecutive sampling periods.'
;

COMMENT ON TABLE "Schedule"
	IS '6-08 Description of the schedule of observation. Note: Schedules are defined in terms of months covered, weekdays covered, hours and minutes covered during each day. A complete definition of a schedule requires specification of the temporalReportingInterval, and may require the specification of diurnalBaseTime.'
;

COMMENT ON COLUMN "Schedule"."Endhour"
	IS 'End hour of schedule (0 to 23)'
;

COMMENT ON COLUMN "Schedule"."Endminute"
	IS 'End minute of schedule (0 to 59)'
;

COMMENT ON COLUMN "Schedule"."Endmonth"
	IS 'End month of schedule (January = 1, December = 12)'
;

COMMENT ON COLUMN "Schedule"."Endweekday"
	IS 'End day of schedule (Monday = 1, Sunday = 7)'
;

COMMENT ON COLUMN "Schedule"."Starthour"
	IS 'Start hour of schedule (0 to 23)'
;

COMMENT ON COLUMN "Schedule"."Startminute"
	IS 'Start minute of schedule (0 to 59)'
;

COMMENT ON COLUMN "Schedule"."Startmonth"
	IS 'Start month of schedule (January = 1, December = 12)'
;

COMMENT ON COLUMN "Schedule"."Startweekday"
	IS 'Start day of schedule (Monday = 1, Sunday = 7)'
;

COMMENT ON TABLE "Surfacecover"
	IS 'A SurfaceCover is a climate zone accompanied by a timestamp indicating the time from which that surface cover class is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple surface cover classes which are valid over different consecutive periods of time. If only a single surface cover class is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Surfacecover"."Surfacecover"
	IS '4-01 The (bio)physical cover on the earth''s surface in the vicinity of the observations from the LandCoverType codelist . 
NOTE: Only applies for surface-based (fixed) observing facilities.'
;

COMMENT ON COLUMN "Surfacecover"."Surfacecoverclassification"
	IS '4-02 Reference to a surface cover classification type from the SurfaceCoverClassificationType codelist. NOTE: only if 4-01 is specified'
;

COMMENT ON COLUMN "Surfacecover"."Validperiod"
	IS 'The time period for which the specified surfaceCover is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next surfaceCover on record. If only one surfaceCover is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Surfaceroughness"
	IS 'A SurfaceRoughness is a specification of surfaceRoughness accompanied by a timestamp indicating the time from which that surfaceRoughness is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple surfaceRoughness specifications which are valid over different consecutive periods of time. If only a single surfaceRoughness is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Surfaceroughness"."Surfaceroughness"
	IS '4-06 surface roughness at the facility. From the SurfaceRoughnessType codelist.'
;

COMMENT ON COLUMN "Surfaceroughness"."Validperiod"
	IS 'The time period for which the specified surfaceRoughness is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next surfaceRoughness on record. If only one surfaceRoughness is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Territory"
	IS 'A Territory is a territory specification accompanied by a timestamp indicating the time from which that territory is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple territories which are valid over different consecutive periods of time. If only a single territory is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Territory"."Territoryname"
	IS '3-02 The territory the observing facility is located in, from the TerritoryType codelist.'
;

COMMENT ON COLUMN "Territory"."Validperiod"
	IS 'The time period for which the specified territory is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next territory on record. If only one territory is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Timezone"
	IS 'A TmeZone is a timeZone specification accompanied by a timestamp indicating the time from which that timeZone is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple timeZone specifications which are valid over different consecutive periods of time. If only a single timeZone is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Timezone"."Timezone"
	IS 'Time zone of the observing facility'
;

COMMENT ON COLUMN "Timezone"."Validperiod"
	IS 'The time period for which the specified climateZone is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next climateZone on record. If only one climateZone is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Topographybathymetry"
	IS 'A TopographyBathymetry is a specification of topography / bathymetry accompanied by a timestamp indicating the time from which that topographyBathymetry specification is considered to be valid. If known, an end time may also be provided. In WIGOS, an ObservingFacility may carry multiple topographyBathymetry specifications which are valid over different consecutive periods of time. If only a single topographyBathymetry is specified, the timestamp is optional.'
;

COMMENT ON COLUMN "Topographybathymetry"."Altitudeordepth"
	IS '4-03 The altitude/depth with respect to mean sea level from the AltitudeOrDepthTypeCodelist'
;

COMMENT ON COLUMN "Topographybathymetry"."Localtopography"
	IS '4-03 The local topography from the LocalTopographyType codelist'
;

COMMENT ON COLUMN "Topographybathymetry"."Relativeelevation"
	IS '4-03 The relative elevation from the RelativeElevationType codelist'
;

COMMENT ON COLUMN "Topographybathymetry"."Topographiccontext"
	IS '4-03 The topographic context from the TopographicContextType codelist'
;

COMMENT ON COLUMN "Topographybathymetry"."Validperiod"
	IS 'The time period for which the specified topographyBathymetry is known to be valid. Normally, this will be specified as a "from" date, implying that the validity extends but does not include the next topographyBathymetry on record. If only one topographyBathymetry is specified for an observing facility, the time stamp is optional.'
;

COMMENT ON TABLE "Wigosmetadatarecord"
	IS 'The WIGOSMetadataRecord is a container for WIGOS information for the purposes of packaging the information for delivery to, or transfer between, systems.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Deployment"
	IS 'A Deployment instance in this record. Note that Deployments may also be encoded inline with the OM_Observation (as part of the Process).'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Equipment"
	IS 'An Equipment instance in this metadata record.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Equipmentlog"
	IS 'An EquipmentLog instance in this metadata record. Note that an EquipmentLog may also be encoded inline with the Equipment instance.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Extension"
	IS 'This extension point is to facilitate the encoding of any other information for complimentary or local purposes such as complying with legislative frameworks.
However it should not be expected that any extension information will be appropriately processed, stored or made retrievable from any WIGOS systems or services. '
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Facility"
	IS 'An ObservingFacility instance in this metadata record.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Facilitylog"
	IS 'A FacilityLog instance in this metadata record. Note that an FacilityLog may also be encoded inline with the ObservingFacility instance.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Facilityset"
	IS 'A FacilitySet instance in this metadata record. The FacilitySet will simply consist of links to ObservingFacilities belonging to the set.'
;

COMMENT ON COLUMN "Wigosmetadatarecord"."Headerinformation"
	IS 'A header section must be included with every WIGOS MetadataRecord.'
;
